name: CI Pipeline
on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main
      - development
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Run unit tests
        run: mvn test

      - name: SonarCloud Scan
        run: mvn verify sonar:sonar \
          -Dsonar.java.source=21 \
          -Dsonar.host.url=${{ vars.SONAR_CLOUD_URL }} \
          -Dsonar.projectKey=${{ vars.KEYCLOAKXP_SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ vars.KEYCLOAKXP_SONAR_ORGANIZATION }} \
          -Dsonar.token=${{ vars.KEYCLOAKXP_SONAR_TOKEN }}
